/* ─────────────────────────────────────────────────────────────────────────────
   Emit the browser icons from the ONE source of the mark.

   `src/assets/mark.json` is imported by `Logo.tsx` and read here. Nothing else
   holds the path data, so the tab icon cannot drift away from the header mark —
   which is exactly what happened the last time the favicon carried its own copy.

   Two outputs:

     public/favicon.svg        — the primary. Deterministic, pure Node, runs in
                                 `prebuild`, safe in CI.
     public/icon-180/192/512   — PNG fallbacks and the apple-touch-icon.
                                 Rasterised with headless Chrome, which is NOT a
                                 build dependency: the step is skipped with a
                                 warning when Chrome is absent, and the committed
                                 PNGs stay as they are. Regenerate deliberately
                                 with `npm run icons` when the mark changes.

   Usage:
     node scripts/build-icons.mjs          # svg only
     node scripts/build-icons.mjs --png    # svg + rasterise
   ───────────────────────────────────────────────────────────────────────────── */

import { readFileSync, writeFileSync, existsSync, mkdirSync, rmSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..')
const pub = resolve(root, 'public')

const mark = JSON.parse(readFileSync(resolve(root, 'src/assets/mark.json'), 'utf8'))
const { padding, radius, light, dark } = mark.icon

// The mark's own viewBox, grown by `padding` on every side. The path data is
// untouched — the inset comes from the viewBox origin, so the two can't diverge.
const [, , w, h] = mark.viewBox.split(/\s+/).map(Number)
const box = `${-padding} ${-padding} ${w + padding * 2} ${h + padding * 2}`

const paths = mark.paths
  .map((p) => `    <path d="${p.d}" stroke-width="${p.strokeWidth}"/>`)
  .join('\n')

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${box}" role="img" aria-label="VeloCare">
  <!-- GENERATED by scripts/build-icons.mjs from src/assets/mark.json. Do not edit:
       edit the JSON and re-run \`npm run icons\`. This is the one place the mark
       carries literal colour — a standalone SVG has no context to inherit, so
       currentColor would resolve to the UA text colour and vanish against a dark
       tab strip. Everywhere else the mark is currentColor, which is what keeps
       the printed sheet chroma 0. -->
  <style>
    .ground { fill: ${light.ground}; }
    .mark { stroke: ${light.mark}; }
    @media (prefers-color-scheme: dark) {
      .ground { fill: ${dark.ground}; }
      .mark { stroke: ${dark.mark}; }
    }
  </style>
  <rect class="ground" x="${-padding}" y="${-padding}" width="${w + padding * 2}" height="${h + padding * 2}" rx="${radius}"/>
  <g class="mark" fill="none" stroke-linecap="${mark.strokeLinecap}" stroke-linejoin="${mark.strokeLinejoin}">
${paths}
  </g>
</svg>
`

mkdirSync(pub, { recursive: true })
writeFileSync(resolve(pub, 'favicon.svg'), svg)
console.log('wrote public/favicon.svg')

if (!process.argv.includes('--png')) process.exit(0)

/* ── PNG, via headless Chrome ─────────────────────────────────────────────────
   PNGs are committed artifacts. Chrome is a local tool for regenerating them,
   never something `npm run build` depends on.
   ─────────────────────────────────────────────────────────────────────────── */

const CHROME = [
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  '/Applications/Chromium.app/Contents/MacOS/Chromium',
  '/usr/bin/google-chrome',
  '/usr/bin/chromium',
].find((p) => existsSync(p))

if (!CHROME) {
  console.warn('! Chrome not found — skipping PNGs. Committed ones are unchanged.')
  process.exit(0)
}

// Light scheme forced: a tab icon baked from whatever the build machine's OS
// theme happened to be would be a genuinely baffling bug to track down.
const forcedLight = svg.replace(/@media \(prefers-color-scheme: dark\) \{[^}]*\{[^}]*\}[^}]*\{[^}]*\}\s*\}/s, '')

for (const size of [180, 192, 512]) {
  const html = `<!doctype html><meta charset="utf-8">
<style>html,body{margin:0;padding:0;background:transparent}svg{display:block;width:${size}px;height:${size}px}</style>
${forcedLight}`
  const tmp = resolve(pub, `.icon-${size}.html`)
  writeFileSync(tmp, html)
  const out = size === 180 ? 'apple-touch-icon.png' : `icon-${size}.png`
  execFileSync(
    CHROME,
    [
      '--headless',
      '--disable-gpu',
      '--hide-scrollbars',
      `--window-size=${size},${size}`,
      `--screenshot=${resolve(pub, out)}`,
      `file://${tmp}`,
    ],
    { stdio: 'ignore' },
  )
  rmSync(tmp)
  console.log(`wrote public/${out}`)
}
